right-click:
   path: "tooltips:icons/right-click.png"
   ascent: 0
   height: 4
left-click:
   path: "tooltips:icons/left-click.png"
   ascent: 0
   height: 4
black-right-click:
   path: "tooltips:icons/black-right-click.png"
   ascent: 0
   height: 4
black-left-click:
   path: "tooltips:icons/black-left-click.png"
   ascent: 0
   height: 4
