name: Better Tooltips
main: fi.septicuss.bettertooltips.Tooltips
version: ${project.version}
api-version: 1.20

author: Septicuss, Rinary

depend: [ ProtocolLib ]
softdepend: [ PlaceholderAPI, ItemsAdder, Oraxen, WorldGuard, WorldEdit, MythicCrucible, MythicMobs, Citizens ]

commands:
   tooltips:
      aliases: [tooltip, tt]
